#!/bin/bash

# ROOT_DIR=$(git rev-parse --show-toplevel)
# DEV_DIR=${ROOT_DIR}/backend/dev

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <audio-file>" >&2
  exit 1
fi

AUDIO_FILE="$1"
WHISPER_DIR="$(dirname "$0")/.."
cd $WHISPER_DIR


curl -X POST http://127.0.0.1:9991/api/stt \
  -F "file=@${AUDIO_FILE}" \
  -F "model=mlx-community/whisper-large-v3-turbo"